### ISSUE TITLE
请教 请教 要想在该日历控件<input type="text" class="calendars" placeholder="选择日期" oninput=""  onpropertychange="" >加入oninput onpropertychange 改如何修改？ 

### ISSUE THREAD

**Issue by huanglei252** [rookie125/mobile-calendar#1]
请教 要想在日历控件中<input type="text" class="calendars" placeholder="选择日期" oninput=""  onpropertychange="" >加入oninput onpropertychange 改如何修改？

**Comment by huanglei252** [comment]
看到了  您写的 jquery change 的方法 实现 oninput  问题解决了 感谢

**Comment by rookie125** [comment]
嗯嗯，欢迎给个star，^_^~

**Comment by huanglei252** [comment]
写的真棒  向您学习 哈哈  必须star

**Comment by rookie125** [comment]
谢啦，也希望该组件对您有帮助

**Comment by huanglei252** [comment]
谢谢您   哈哈

**Comment by shenfusheng** [comment]
我用谷歌浏览器模拟手机打开，插件不支持滑动切换是怎么回事

**Comment by shenfusheng** [comment]
建议增加一个超过两个月的时间不可选择，当然具体多长时间用户可以自己定义，这样就可以把日期控制到一个特定的区间内选择了

**Comment by rookie125** [comment]
chrome浏览器如果要支持手势的话，需要在控制台开启一下的哦。还有谢谢您的这个建议哈，这个我修改一下

**Comment by rookie125** [comment]
@shenfusheng chrome浏览器如果要支持手势的话，需要在控制台开启一下的哦。还有谢谢您的这个建议哈，这个我修改一下
