### ISSUE TITLE
禁用日期不能是将来

### ISSUE THREAD

**Issue by c4ys** [rookie125/mobile-calendar#17]
可以通过设置pass禁用过去时间，但是不能禁用将来时间shield只能是每天，通常报表需求中肯定是要求只能选择过去的时间，而不是将来的时间。

建议直接采用minDate和maxDate

**Comment by rookie125** [comment]
@c4ys 是的，这也是比较常见的需求，清明节期间发布个新版本，会支持可设置minDate和maxDate功能

**Comment by rookie125** [comment]
@c4ys minDate 和 maxDate限制已经添加了
