### ISSUE TITLE
如果是动态增加的日期，要怎么进行处理呢

### ISSUE THREAD

**Issue by yuanjianhua** [rookie125/mobile-calendar#18]
如果是动态增加的日期，要怎么进行处理呢

**Comment by rookie125** [comment]
@yuanjianhua 可以说一下你的使用情况、场景

**Comment by yuanjianhua** [comment]
@比如，我动态新增一个日期文本框，如果再次把calendar focus事件再次绑定上去呢

**Comment by yuanjianhua** [comment]
@rookie125  比如，我动态新增一个日期文本框，如果再次把calendar focus事件再次绑定上去呢

**Comment by rookie125** [comment]
@yuanjianhua 先删掉以前的版本，然后重新执行一下 `npm install mobile-calendar`，在你动态添加了一个元素之后，再调用一下`new Calendar()`就可以了
