### ISSUE TITLE
我用谷歌浏览器模拟手机打开，插件不支持滑动切换是怎么回事建议增加一个超过两个月的时间不可选择，当然具体多长时间用户可以自己定义，这样就可以把日期控制到一个特定的区间内选择了

### ISSUE THREAD

**Issue by shenfusheng** [rookie125/mobile-calendar#3]

**Comment by rookie125** [comment]
@shenfusheng  在控制台里面按ESC键可以弹出下面的选项
![image](https://cloud.githubusercontent.com/assets/11306273/8614511/d81483a6-271c-11e5-9649-47d9e5cf701c.png)

**Comment by shenfusheng** [comment]
有开启还是没用
![image](https://cloud.githubusercontent.com/assets/9476838/8614591/934b2292-271d-11e5-93e2-f2494a7f5ed0.png)

**Comment by rookie125** [comment]
@shenfusheng 在chrome里面模拟触摸有时候还有个毛病，你试试我这个方法看看：
在浏览器 新开一个标签，然后打开这个模拟手机的界面，再把地址粘贴到地址栏回车，就是先开模拟 的界面再输入浏览器的地址

**Comment by shenfusheng** [comment]
真正的手机端上就不会有问题是吗

**Comment by rookie125** [comment]
@shenfusheng 不会的哦，我刚刚clone一下来也可以呢

**Comment by shenfusheng** [comment]
好的，先开模拟在粘贴地址就可以了，谢谢

**Comment by rookie125** [comment]
@shenfusheng 不客气，感谢使用，因你们更加精彩^_^

**Comment by shenfusheng** [comment]
还有一个建议，就是不要在插件里面重新定义html的字号，这样可能会对插件以外的区域造成影响，插件的样式应该只在插件内部有效，而不会重写全局的样式。

![qq 20150710164002](https://cloud.githubusercontent.com/assets/9476838/8615071/2af02864-2722-11e5-9ae1-f9c4ec2b9ca7.png)

**Comment by rookie125** [comment]
@shenfusheng 嗯嗯，对，当初写的时候调试习惯了一上来就搞html的字体大小，连同上面的建议我修改一下[抱拳]
