### ISSUE TITLE
头部的月份显示的是12月，但其实是11月。

### ISSUE THREAD

**Issue by zuley** [rookie125/mobile-calendar#4]
还有下载的DOM打开不显示日历，一看是被隐藏了。
只有去到样式表上删除.calendar .calendar-list上的相关样式才能正常显示

**Comment by rookie125** [comment]
@zuley README的演示地址我重新启动了，你可以先看看演示地址是否存在此问题

**Comment by zuley** [comment]
你的演示站是没有问题的，但是我下载过来的有问题。。。显示的值是11，实际data-val上是10
![20151110143525](https://cloud.githubusercontent.com/assets/3047318/11056036/69cbb052-87b8-11e5-9864-57261a616b21.png)

**Comment by rookie125** [comment]
@zuley data-value属性那里其实是正确的，JavaScript中月份是0月~11月，而我们正常看的是1月~12月，data-value那里是给代码看的，没关系的，样式那里可能存在的问题是样式冲突

**Comment by rookie125** [comment]
@zuley 但是看你图片，月份对应的日期确实不正确

**Comment by zuley** [comment]
对啊，我点击输入框的时候展开的日期控件顶部显示的是2015年11月。但下方对应的日历其实是10月的

**Comment by rookie125** [comment]
@zuley 我down到本地发现也是正常的，你单独在你本地运行下看看是否还存在这个问题。另外我同步了下文件

**Comment by zuley** [comment]
为什么会这么奇怪 = = ，我放在桌面运行也是这个问题，放本地服务器里还是一样的，换了浏览器也是。

**Comment by zuley** [comment]
我同事电脑上就没问题，我问他要的他那边的包到我这里在谷歌下正常，去火狐还是会有问题

**Comment by rookie125** [comment]
@zuley 修复了火狐的问题了
