### ISSUE TITLE
我在i6s的时候发现点击或者是滑动的时候是有点延迟的

### ISSUE THREAD

**Issue by semi-xi** [rookie125/mobile-calendar#6]
不知道是机型问题还是事件本身的绑定问题，另外就是在年份左右滑动的时候可以切换年份，但是感觉滑了几次也不一定会换的~滑回来的时候也不一定有动画。可以去试下~
另外感谢提供插件

**Comment by rookie125** [comment]
@semi-xi  
是的，我在6上看了，确实有你说的问题，尽快修复，如你在使用的版本中修复了也可以贡献你的代码
