### ISSUE TITLE
发现一个小问题

### ISSUE THREAD

**Issue by 531431988** [rookie125/mobile-calendar#7]
mobilebone.js切页时calendar不能显示

**Comment by rookie125** [comment]
@531431988  这段时间忙着公司项目的事忘回复了，趁着五一假期可以看看这个问题

**Comment by 531431988** [comment]
大神已经解决了。感谢大神的无私
// window.addEventListener('load', function(){
    //     new Calendar();
    // }, false);
解决如下：
    window.Calendar=Calendar;
    return Calendar;

**Comment by rookie125** [comment]
@531431988 哈哈哈，解决了就好，感觉支持
