### ISSUE TITLE
代码逻辑问题

### ISSUE THREAD

**Issue by TroyIrvo** [rookie125/mobile-calendar#9]
demo不可选过期日期的时候发现该问题。 2016-01是可选的
![image](https://cloud.githubusercontent.com/assets/19662959/21978539/03378696-dc16-11e6-8fd8-36123fd4b8c9.png)

demo指定可选日期的时候发现该问题。 2014竟然是可选的， 指定的开始日期是2015、05、16
![image](https://cloud.githubusercontent.com/assets/19662959/21978621/4f9914a0-dc16-11e6-8417-764e0a99e971.png)

**Comment by rookie125** [comment]
@TroyIrvo 是的，我发现了，我会尽快修复

**Comment by rookie125** [comment]
@TroyIrvo  修复了，重新npm 安装一下就可以了
